### ISSUE TITLE
[Quest] Duplicated Quests

### ISSUE THREAD

**Issue by Althin** [Valhalla-Gaming/Tracker#1041]
In Ammen Vale in Azuremyst Isle quests from following NPC are duplicated:
*Technician Zhanaa: http://www.wowhead.com/npc=17071/technician-zhanaa 
  - Quest "Spare Parts": http://www.wowhead.com/quest=9305/spare-parts

*Vindicator Aldar: http://www.wowhead.com/npc=16535/vindicator-aldar
  - Quest "Inoculation": http://www.wowhead.com/quest=9303/inoculation

**Comment by Guybrush-Hellscream** [comment]
Fixed.

**Comment by zwei7** [comment]
It's not fixed, look at the quest log in this screen, there are 2 of these quests I just completed.
![wowscrnshot_110215_031210](https://cloud.githubusercontent.com/assets/15259298/10876946/858f159a-810f-11e5-939f-afd68be46602.jpg)

**Comment by Guybrush-Hellscream** [comment]
Thank you for your input.
