### ISSUE TITLE
Bug with Fishing bob

### ISSUE THREAD

**Issue by narik89** [Valhalla-Gaming/Tracker#1386]
Hi Team,

Ingame name : Druider (druid tauren)

The server is awesome for playing. I really like the 1x rather than the other. Congrats on that.

I have a bug in my fishing. When i do fishing, my fishing bobber does not give any indication that a fish has been captured. Usually the bobber goes into water and comes out when a fish is caught. 

I have tried in many locations. I cleared caches. I have used fishing pole. Attached even lure to it.

I just get message that Your fish has got away. Randomly when i click it says No fishes hooked.

Could you help me on this?

Thanks
Druider

**Comment by Malae1** [comment]
This should have been fixed, perhaps it has resurfaced. I'll push this up the list.

**Comment by narik89** [comment]
Hello,

Any status regarding this? i still see that we are not able to fish?

Thanks
Druider

**Comment by Malae1** [comment]
After checking it does appear that the bobber does not jiggle any longer.

**Comment by narik89** [comment]
Hello,

Any status regarding this? i still see that we are not able to fish?

Thanks
Druider

**Comment by Malae1** [comment]
It seems very hit or miss, sometimes it works, sometimes it doesn't.

**Comment by soongtype** [comment]
I've been having this issue as well. It seems like it works a few times, then there's a long streak of fish getting away, then it will work a few more times.
