### ISSUE TITLE
Alchemy recipe leaning

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#2047]
Hey i have Alchemy stuck on 535 and made over 700 http://www.wowhead.com/spell=114751/alchemists-rejuvenation and learned two low level potions, and just learning those seems the chances on making the potions a bit frustrating becuase the chances should be higher according to wowhead, i will keep making stuff and hope a lil luck for a change.

**Comment by Tregeta** [comment]
fixed previous update

**Comment by Luminescent-Valhalla** [comment]
please take another look at this mad over 100  Alchemist's Rejuvenation potions and am still missing MoP discover-able recipes.

**Comment by Tregeta** [comment]
Which ones are you missing? I am able to learn just fine, need more information.

**Comment by Luminescent-Valhalla** [comment]
Ok so i took another loot at what discoveries am missing and it seems that only one is missing for me [Riddle of Steel](www.wowhead.com/spell=130326/riddle-of-steel) as you can see in this screen below i have a addon showing missing discoveries from MoP along with the mats to make 140 potions from MoP
![wowscrnshot_041316_065731](https://cloud.githubusercontent.com/assets/13806368/14484247/d0fee2be-0146-11e6-8d3e-6e88c5c84316.jpg)

Now as you can see 140 potions later the recipe still has not been discovered thats over 240 potions in less than 24 hours to try and discover Riddle of Steel.

![wowscrnshot_041316_070122](https://cloud.githubusercontent.com/assets/13806368/14484265/fabe7dbc-0146-11e6-83e6-5d57d31bd424.jpg)

**Comment by Luminescent-Valhalla** [comment]
ok so gathered more regents to craft another 140 of them as you can see below 
![wowscrnshot_041316_072941](https://cloud.githubusercontent.com/assets/13806368/14484664/d0cb15f8-0149-11e6-83e1-590fa5e35438.jpg)

After crafting another 140 as you can see in my bags now 2 rows of 140 potions (in the image below) all the same all able to learn mop discoverable designs and still no riddle of steel design.

![wowscrnshot_041316_073353](https://cloud.githubusercontent.com/assets/13806368/14484746/5612e1e6-014a-11e6-9cd1-64a2c876666e.jpg)


So i can confirm this is indeed not working as it should thats 280 potions today along not counting all the others i  have made in the past.

**Comment by Tregeta** [comment]
I have found the reason why which is quite simple as this data was not available shown to be discover-able on the link: http://www.wowhead.com/guide=1067/mists-of-pandaria-alchemy-overview

Nevertheless, will be fixed next update.

**Comment by Luminescent-Valhalla** [comment]
Thanks for the update tregata
