### ISSUE TITLE
Protection skills/talents

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#222]
There's no bladed armor passive for being protection spec, it adds 100% of your armor as attack power. Hammer of Righteousness doesn't do AoE damage. Holy Wrath does nothing. I'm assuming Word of Glory and all other holy power skills aren't working properly yet, as Word of Glory does nothing for a cast time.

**Comment by Max-Hellscream** [comment]
Hammer of Roughteousness and Word of Glory should be working correctly.

**Comment by tribaljet** [comment]
Bladed Armor still doesn't seem to be working, as with Bonus Armor not being taken into account when gear that has it is equipped.

**Comment by Moustachos** [comment]
Ref #2266
