### ISSUE TITLE
Hunter - Marksmen specialization

### ISSUE THREAD

**Issue by kaneles** [Valhalla-Gaming/Tracker#2557]
The MM Hunter has some problems such as the talents Posthaste , Stampede , Murder of Crows and  
more then a few glyphs.The real problem is that Chimaera shot which is a core ability isn't working and it's makeing the MM unplayable.So please fix all the classes before anything else.

Thank you
Keep up the good work.

**Comment by Guybrush-Hellscream** [comment]
You need to be more specific about what's not working on those spells. The more details, the faster it is solved.

**Comment by POUREDOR** [comment]
ok ill explain the posthaste doesn't removes slowing effects murder of crows doesnt summon crows chimera shot doesnt do enough damage and it will only hit one target instead of two

**Comment by Tuf-Interceptor** [comment]
Moving on from the forum as instructred by Game Master.

Few core, general and talent tree skills that are still not working as per current moment. (At least, what I have discovered so far.)

Marksmanship's - Chimaera Shot (No Damage at all, only activate auto attack)
Beast Mastery's - Kill Command (No Damage at all, only activate pet to attack target)
Traps and Flare

Talent Tree :
- Tier 1 : Posthaste, Narrow Escape (Doesn't Stick Enemy in place)
- Tier 3 : Spirit Bond (Doesn't heal both player and pet at all)
- Tier 5 : Murder of Crow (No Crows - No Damage), Stampede (No Pets - No Damage)

Without these skills, Hunter is pretty much a handicapped class in both PvE and PvP area.

Also, Pet's Health - A bit on the low side to my understanding. (Do correct me if I'm wrong though)

Seeing the hardworking and dedicated devs, I believe these issues will be able to get fixed in no time at all.

Thank you in advance to the staff for looking into these matter.

**Comment by Tregeta** [comment]
As stating several times, please check BEFORE posting any bugs, they may be on the tracker already. 
Posthaste Ref #346, #2029, #2317
Narrow Escape Ref #461, 2798
Spirit Bond Ref #2367, #2797
Murder of Crows Ref #2797

**Comment by Moustachos** [comment]
Ref #2266
