### ISSUE TITLE
Northshire

### ISSUE THREAD

**Issue by xLuf** [Valhalla-Gaming/Tracker#2637]
- [Stormwind Royal Guard](http://www.wowhead.com/npc=42218/stormwind-royal-guard) those on horses have double spawn
  - Sometimes their formation is a bit off
- [Northshire Guard](http://www.wowhead.com/npc=1642/northshire-guard) shouldn't be spawned in Northshire, only in the entrance (on retail they are **sometimes** spawned, but after a while they disappear, seems like an odd blizzard bug)
- [Stormwind Infantry](http://www.wowhead.com/npc=49869/stormwind-infantry) some of them aren't fighting with the worgs
- [Blackrock Spy](http://www.wowhead.com/npc=49874/blackrock-spy) they should've small chance they say something (now it's 100%)
- [Stormwind Infantry](http://www.wowhead.com/npc=50047/injured-stormwind-infantry) shouldn't have special mouse icon on mouse over without quest [Fear No Evil](http://www.wowhead.com/quest=28806/fear-no-evil)
  - You can click multiple times on one Infantry (if you are fast enough)
  - When you are doing quest [Fear No Evil](http://www.wowhead.com/quest=28806/fear-no-evil) there are no glowing "stars" above them
  - They don't do any emotes when you revive them
  - When they respawn, they have under their name <Name's Minion>
- [Brother Paxton](http://www.wowhead.com/npc=951/brother-paxton) should start moving earlier after his heal
  - His waypoints are a bit off
  - [Prayer of Healing](http://www.wowhead.com/spell=93091/prayer-of-healing) is healing worgs
  - [Power Word: Fortitude](http://www.wowhead.com/spell=13864/power-word-fortitude) shouldn't be cast on players
  - He should cast Penance (don't know ID)
- [Blackrock Invader](http://www.wowhead.com/npc=42937/blackrock-invader) they should've small chance they say something (now it's 100%)
- [Vineyard Fire](http://www.wowhead.com/npc=42940/northshire-vineyards-fire-trigger) should've smaller respawn time + there should be more of them spawned
- [Dane Windlow](http://www.wowhead.com/npc=6373/dane-winslow) Abandon Imp gossip should see only warlocks
  - He doesn't cast [Summon Imp](http://www.wowhead.com/spell=11939/summon-imp)
- [Falkhaan Isenstrider](http://www.wowhead.com/npc=6774/falkhaan-isenstrider) is spawned on a different place than he should be
- [Blackrock Work](http://www.wowhead.com/npc=49871/blackrock-worg) **[this one](http://i.imgur.com/1LNPYSG.jpg)** shouldn't be spawned
- Names and descriptions under portraits don't show up

**Comment by HellscreamWoW** [comment]
Marshal McBride and the Stormwind Royal Guards are now fixed.

The Stormwind Infantry don't chase worgs, even on retail. They will only fight a worg that comes close to them. So this isn't an issue.

**Comment by xLuf** [comment]
As you can see [here](http://i.imgur.com/qscpRRl.jpg) they are standing in melee range and still don't fight.
