### ISSUE TITLE
Draenor Inscription

### ISSUE THREAD

**Issue by Adelpho** [Valhalla-Gaming/Tracker#3095]
The NPC http://www.wowhead.com/npc=87551 is supposed to sell this item http://www.wowhead.com/item=111923 which raises your skill cap to 700 and teaches you a few draenor recipes. 
But this item is missing from this vendor NPC, making it impossible to learn Draenor inscription.

**Comment by Luminescent-Hellscream** [comment]
also when you obtain  [Draenor Inscription](http://www.wowhead.com/item=111923/draenor-inscription)   The recipes you automatically learn are:  [War Paints](http://www.wowhead.com/spell=169081),  [Secrets of Draenor Inscription](http://www.wowhead.com/spell=177045),  [Research: Warbinder's Ink](http://www.wowhead.com/spell=167950),  [Laughing Tarot](http://www.wowhead.com/spell=175390), [Ocean Tarot](http://www.wowhead.com/spell=175389),  [Savage Tarot](http://www.wowhead.com/spell=175392),  [Card of Omens](http://www.wowhead.com/spell=166669),  [Warbinder's Ink](http://www.wowhead.com/spell=178497)

**Comment by Luminescent-Hellscream** [comment]
Also even with 1/700 skill you are not able to mill Draenor herbs like you should be able to.

**Comment by Tregeta** [comment]
should be fixed both milling & vendor/training

**Comment by VictorTyne** [comment]
This wasn't fixed, as referenced in https://github.com/Valhalla-Gaming/Tracker/issues/8203 

Leaving the note for people who come looking for why draenor inscription isn't working so they don't try unlearning and relearning it.
