### ISSUE TITLE
Flags/bases in Arathi Basin (possibly in Battle for Gilneas too)

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#3861]
Capping flag/base in Arathi Basin (Control the Base bgs) should last 8 sec and be interruptable by damage. Currently it last 8 sec BUT you can't interrupt someones capping unless you stun/fear/seduce him.

**Comment by Hangun** [comment]
Agree it should

**Comment by Luminescent-Hellscream** [comment]
Flags need to be fixed asap you can cap them while stealthed and are able to take damage while capping which should not happen this is also presant in battle for gilneas too

**Comment by EPS1L0N** [comment]
tested AB & WSG, stealth was removed. pretty sure this was fixed not long ago. if you're able to reproduce it again I'll reopen

**Comment by Luminescent-Valhalla** [comment]
capping on 25th jan 2016 was still not working as it should forgot i had this screenshot 
(looked through them all when saw this)

[Druid stealth cap](http://i.imgur.com/n0RplC2.jpg)

**Comment by EPS1L0N** [comment]
next update check it :P
