### ISSUE TITLE
[Quest] A Curse We Cannot lift

### ISSUE THREAD

**Issue by julkoh** [Valhalla-Gaming/Tracker#3965]
This quest is not completable because the NPC (Lurking Worgen) is untargetable, and the item (Harris's Ampule) does nothing.

Quest : http://www.wowhead.com/quest=26720
NPC : http://www.wowhead.com/npc=43814
Item : http://www.wowhead.com/item=60206

**Comment by GM-Pyromanic** [comment]
Fixed in last update.

**Comment by roirraWedorehT** [comment]
Still not working for me.  Same as what the original report said.  That is, I can target him but not able to actually do anything with the ampule on him.

**Comment by Cidragon** [comment]
That's right, the script is wrong. This issue will be fixes in next update.

**Comment by roirraWedorehT** [comment]
Thanks!!!

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.

**Comment by habagatamihan** [comment]
Still not working. I tried using the quest item against the target but it keeps saying "invalid target". But I was able to kill the "Lurking Worgen".
