### ISSUE TITLE
[Demon Hunters] Doublejump/glide thing.

### ISSUE THREAD

**Issue by Anderzenn** [Valhalla-Gaming/Tracker#5940]
It is almost. ALMOST perfect :D 
Only thing is some weird issues, uploaded these to videos so you can see the difference.

Retail:
https://www.youtube.com/watch?v=Y76_M6MixVg&feature=youtu.be

Valhalla:
https://www.youtube.com/watch?v=2iV1r6XH1l0&feature=youtu.be

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Anderzenn** [comment]
I'd like to say this hasn't been fixed. It still doesn't give you the "push" it's supposed to like in the video.

**Comment by Moustachos** [comment]
> I'd like to say this hasn't been fixed. It still doesn't give you the "push" it's supposed to like in the video.

Will be fixed on next update.
